/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as AwaitingApprovalRouteImport } from './routes/awaiting-approval'
import { Route as BlockedRouteImport } from './routes/blocked'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as UsersRouteImport } from './routes/users'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminMembershipsRouteImport } from './routes/admin.memberships'
import { Route as AdminOrganizationsRouteImport } from './routes/admin.organizations'
import { Route as AdminPermissionsRouteImport } from './routes/admin.permissions'
import { Route as AdminTicketedEventsRouteImport } from './routes/admin.ticketed-events'
import { Route as AdminUniversitiesRouteImport } from './routes/admin.universities'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppEventsRouteImport } from './routes/app.events'
import { Route as AppTicketsRouteImport } from './routes/app.tickets'
import { Route as UsersIndexRouteImport } from './routes/users.index'
import { Route as AppEventsIndexRouteImport } from './routes/app.events.index'
import { Route as AdminEventsEventIdTicketsRouteImport } from './routes/admin.events.$eventId.tickets'
import { Route as AppEventsEventIdTicketsRouteImport } from './routes/app.events.$eventId.tickets'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AwaitingApprovalRoute = AwaitingApprovalRouteImport.update({
  id: '/awaiting-approval',
  path: '/awaiting-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const BlockedRoute = BlockedRouteImport.update({
  id: '/blocked',
  path: '/blocked',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembershipsRoute = AdminMembershipsRouteImport.update({
  id: '/memberships',
  path: '/memberships',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationsRoute = AdminOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPermissionsRoute = AdminPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTicketedEventsRoute = AdminTicketedEventsRouteImport.update({
  id: '/ticketed-events',
  path: '/ticketed-events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUniversitiesRoute = AdminUniversitiesRouteImport.update({
  id: '/universities',
  path: '/universities',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppEventsRoute = AppEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AppRoute,
} as any)
const AppTicketsRoute = AppTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AppRoute,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersRoute,
} as any)
const AppEventsIndexRoute = AppEventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEventsRoute,
} as any)
const AdminEventsEventIdTicketsRoute =
  AdminEventsEventIdTicketsRouteImport.update({
    id: '/$eventId/tickets',
    path: '/$eventId/tickets',
    getParentRoute: () => AdminEventsRoute,
  } as any)
const AppEventsEventIdTicketsRoute = AppEventsEventIdTicketsRouteImport.update({
  id: '/$eventId/tickets',
  path: '/$eventId/tickets',
  getParentRoute: () => AppEventsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/awaiting-approval': typeof AwaitingApprovalRoute
  '/blocked': typeof BlockedRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/users': typeof UsersRouteWithChildren
  '/admin/events': typeof AdminEventsRouteWithChildren
  '/admin/memberships': typeof AdminMembershipsRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/ticketed-events': typeof AdminTicketedEventsRoute
  '/admin/universities': typeof AdminUniversitiesRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/events': typeof AppEventsRouteWithChildren
  '/app/tickets': typeof AppTicketsRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/users/': typeof UsersIndexRoute
  '/app/events/': typeof AppEventsIndexRoute
  '/admin/events/$eventId/tickets': typeof AdminEventsEventIdTicketsRoute
  '/app/events/$eventId/tickets': typeof AppEventsEventIdTicketsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/awaiting-approval': typeof AwaitingApprovalRoute
  '/blocked': typeof BlockedRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/events': typeof AdminEventsRouteWithChildren
  '/admin/memberships': typeof AdminMembershipsRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/ticketed-events': typeof AdminTicketedEventsRoute
  '/admin/universities': typeof AdminUniversitiesRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/tickets': typeof AppTicketsRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/users': typeof UsersIndexRoute
  '/app/events': typeof AppEventsIndexRoute
  '/admin/events/$eventId/tickets': typeof AdminEventsEventIdTicketsRoute
  '/app/events/$eventId/tickets': typeof AppEventsEventIdTicketsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/awaiting-approval': typeof AwaitingApprovalRoute
  '/blocked': typeof BlockedRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/users': typeof UsersRouteWithChildren
  '/admin/events': typeof AdminEventsRouteWithChildren
  '/admin/memberships': typeof AdminMembershipsRoute
  '/admin/organizations': typeof AdminOrganizationsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/ticketed-events': typeof AdminTicketedEventsRoute
  '/admin/universities': typeof AdminUniversitiesRoute
  '/admin/users': typeof AdminUsersRoute
  '/app/events': typeof AppEventsRouteWithChildren
  '/app/tickets': typeof AppTicketsRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/users/': typeof UsersIndexRoute
  '/app/events/': typeof AppEventsIndexRoute
  '/admin/events/$eventId/tickets': typeof AdminEventsEventIdTicketsRoute
  '/app/events/$eventId/tickets': typeof AppEventsEventIdTicketsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/awaiting-approval'
    | '/blocked'
    | '/login'
    | '/signup'
    | '/users'
    | '/admin/events'
    | '/admin/memberships'
    | '/admin/organizations'
    | '/admin/permissions'
    | '/admin/ticketed-events'
    | '/admin/universities'
    | '/admin/users'
    | '/app/events'
    | '/app/tickets'
    | '/admin/'
    | '/app/'
    | '/users/'
    | '/app/events/'
    | '/admin/events/$eventId/tickets'
    | '/app/events/$eventId/tickets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/awaiting-approval'
    | '/blocked'
    | '/login'
    | '/signup'
    | '/admin/events'
    | '/admin/memberships'
    | '/admin/organizations'
    | '/admin/permissions'
    | '/admin/ticketed-events'
    | '/admin/universities'
    | '/admin/users'
    | '/app/tickets'
    | '/admin'
    | '/app'
    | '/users'
    | '/app/events'
    | '/admin/events/$eventId/tickets'
    | '/app/events/$eventId/tickets'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/awaiting-approval'
    | '/blocked'
    | '/login'
    | '/signup'
    | '/users'
    | '/admin/events'
    | '/admin/memberships'
    | '/admin/organizations'
    | '/admin/permissions'
    | '/admin/ticketed-events'
    | '/admin/universities'
    | '/admin/users'
    | '/app/events'
    | '/app/tickets'
    | '/admin/'
    | '/app/'
    | '/users/'
    | '/app/events/'
    | '/admin/events/$eventId/tickets'
    | '/app/events/$eventId/tickets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  AwaitingApprovalRoute: typeof AwaitingApprovalRoute
  BlockedRoute: typeof BlockedRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  UsersRoute: typeof UsersRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awaiting-approval': {
      id: '/awaiting-approval'
      path: '/awaiting-approval'
      fullPath: '/awaiting-approval'
      preLoaderRoute: typeof AwaitingApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocked': {
      id: '/blocked'
      path: '/blocked'
      fullPath: '/blocked'
      preLoaderRoute: typeof BlockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/memberships': {
      id: '/admin/memberships'
      path: '/memberships'
      fullPath: '/admin/memberships'
      preLoaderRoute: typeof AdminMembershipsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/organizations': {
      id: '/admin/organizations'
      path: '/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AdminOrganizationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/permissions': {
      id: '/admin/permissions'
      path: '/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AdminPermissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ticketed-events': {
      id: '/admin/ticketed-events'
      path: '/ticketed-events'
      fullPath: '/admin/ticketed-events'
      preLoaderRoute: typeof AdminTicketedEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/universities': {
      id: '/admin/universities'
      path: '/universities'
      fullPath: '/admin/universities'
      preLoaderRoute: typeof AdminUniversitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/events': {
      id: '/app/events'
      path: '/events'
      fullPath: '/app/events'
      preLoaderRoute: typeof AppEventsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tickets': {
      id: '/app/tickets'
      path: '/tickets'
      fullPath: '/app/tickets'
      preLoaderRoute: typeof AppTicketsRouteImport
      parentRoute: typeof AppRoute
    }
    '/users/': {
      id: '/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof UsersRoute
    }
    '/app/events/': {
      id: '/app/events/'
      path: '/'
      fullPath: '/app/events/'
      preLoaderRoute: typeof AppEventsIndexRouteImport
      parentRoute: typeof AppEventsRoute
    }
    '/admin/events/$eventId/tickets': {
      id: '/admin/events/$eventId/tickets'
      path: '/$eventId/tickets'
      fullPath: '/admin/events/$eventId/tickets'
      preLoaderRoute: typeof AdminEventsEventIdTicketsRouteImport
      parentRoute: typeof AdminEventsRoute
    }
    '/app/events/$eventId/tickets': {
      id: '/app/events/$eventId/tickets'
      path: '/$eventId/tickets'
      fullPath: '/app/events/$eventId/tickets'
      preLoaderRoute: typeof AppEventsEventIdTicketsRouteImport
      parentRoute: typeof AppEventsRoute
    }
  }
}

interface AdminEventsRouteChildren {
  AdminEventsEventIdTicketsRoute: typeof AdminEventsEventIdTicketsRoute
}

const AdminEventsRouteChildren: AdminEventsRouteChildren = {
  AdminEventsEventIdTicketsRoute: AdminEventsEventIdTicketsRoute,
}

const AdminEventsRouteWithChildren = AdminEventsRoute._addFileChildren(
  AdminEventsRouteChildren,
)

interface AdminRouteChildren {
  AdminEventsRoute: typeof AdminEventsRouteWithChildren
  AdminMembershipsRoute: typeof AdminMembershipsRoute
  AdminOrganizationsRoute: typeof AdminOrganizationsRoute
  AdminPermissionsRoute: typeof AdminPermissionsRoute
  AdminTicketedEventsRoute: typeof AdminTicketedEventsRoute
  AdminUniversitiesRoute: typeof AdminUniversitiesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEventsRoute: AdminEventsRouteWithChildren,
  AdminMembershipsRoute: AdminMembershipsRoute,
  AdminOrganizationsRoute: AdminOrganizationsRoute,
  AdminPermissionsRoute: AdminPermissionsRoute,
  AdminTicketedEventsRoute: AdminTicketedEventsRoute,
  AdminUniversitiesRoute: AdminUniversitiesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppEventsRouteChildren {
  AppEventsIndexRoute: typeof AppEventsIndexRoute
  AppEventsEventIdTicketsRoute: typeof AppEventsEventIdTicketsRoute
}

const AppEventsRouteChildren: AppEventsRouteChildren = {
  AppEventsIndexRoute: AppEventsIndexRoute,
  AppEventsEventIdTicketsRoute: AppEventsEventIdTicketsRoute,
}

const AppEventsRouteWithChildren = AppEventsRoute._addFileChildren(
  AppEventsRouteChildren,
)

interface AppRouteChildren {
  AppEventsRoute: typeof AppEventsRouteWithChildren
  AppTicketsRoute: typeof AppTicketsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppEventsRoute: AppEventsRouteWithChildren,
  AppTicketsRoute: AppTicketsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface UsersRouteChildren {
  UsersIndexRoute: typeof UsersIndexRoute
}

const UsersRouteChildren: UsersRouteChildren = {
  UsersIndexRoute: UsersIndexRoute,
}

const UsersRouteWithChildren = UsersRoute._addFileChildren(UsersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  AwaitingApprovalRoute: AwaitingApprovalRoute,
  BlockedRoute: BlockedRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  UsersRoute: UsersRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
